# Generated by Django 3.0.7 on 2020-08-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading', models.TextField()),
                ('loadingNum', models.FloatField(max_length=5)),
                ('fight_id', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='dkpadd',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dkploot',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
